version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    steps:
      - attach_workspace:
          at: .
      - run: npm run lint
  test:
    steps:
      - attach_workspace:
          at: .
      - run: npm run test
workflows:
  version: 2
  build-test-lint:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
